spring:
  datasource:
    url: jdbc:mysql://rootcause-analyzer-db.c9gsyq60k7ci.ap-south-1.rds.amazonaws.com:3306/rootcauseanalyzer
    username: admin
    password: RootCause1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:
  region: ap-south-1

open:
  api:
    key: YOUR_OPENAI_KEY