spring:
  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/sys?sslMode=VERIFY_IDENTITY
    username: dsazNMN7CcKLoHz.root
    password: 3h3UwSMBv7BEosAp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  open:
    api:
      key: your-openai-key-here